### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by npkeerthi**
@juliaferraioli  Hey I have added a Favicon to your project check it

### CODE REVIEW

**Comment by npkeerthi** [comment]
> @juliaferraioli Hey I have added a Favicon to your project check it

But I did not understood the format of your index.html so I couldn't edit the code properly .
If you can suggest something I'll try to understand 

actually we just need to add 
<link rel="icon" href="favicon.ico" type="image/x-icon" />
this in head of html if its in normal html format 
just saying it to let you know why it was a problem to me

**Comment by juliaferraioli** [comment]
Hi @npkeerthi, thanks for your PR! This site uses [Hugo](https://gohugo.io/) as a static site generator. If you go into the [config.toml](https://github.com/opensourcestories/opensourcestories.org/blob/main/config.toml) file, you'll see an empty place for the favicon. In order to make the favicon work, you need to:

- [ ] Place the `favicon.ico` file in the `static/` directory
- [ ] Add the string `favicon.ico` to the `config.toml` file (ex: `favicon = "favicon.ico"`)

No editing of html needed! Please let me know if you have any questions.

**Review by juliaferraioli — CHANGES_REQUESTED** [review]
Please update your PR to use the approach I outlined in the conversation, thanks!

**Comment by npkeerthi** [comment]
@juliaferraioli  I have made changes according to what you have suggested 
Once check it and have a review 
and tell me if I need to do something additional

**Review by juliaferraioli — CHANGES_REQUESTED** [review]
Looking good! Just a couple more changes:

- [ ] remove the `favicon.ico` file from the root of the repo
- [ ] move `static/images/favicon.ico` to `static/favicon.ico` (you just went one level too far)

You can verify that everything worked as expected by clicking on the [deploy preview](https://deploy-preview-37--opensourcestories.netlify.app/) that the netlify bot links to in the comment.

Thanks!

**Review by juliaferraioli — APPROVED** [review]
Looks great! Thank you @npkeerthi for contributing to Open Source Stories! 🎉

**Comment by npkeerthi** [comment]
@juliaferraioli Check it again now ..I hope this will be the final review😄

**Comment by npkeerthi** [comment]
@juliaferraioli nice working with you . BTW I couldn't see any changes from that [Deploy preview](https://deploy-preview-37--opensourcestories.netlify.app/)
can I know why

**Comment by juliaferraioli** [comment]
You may have to shift+reload for them to show up. Browsers tend to cache the favicons pretty heavily, but I can confirm that it shows up in the tab!

**Comment by npkeerthi** [comment]
Hey @juliaferraioli 

> You may have to shift+reload for them to show up. Browsers tend to cache the favicons pretty heavily, but I can confirm that it shows up in the tab!

Yeah It did work after that. Thanks❤️ Bye

**Pull request merged**
